name: Hello-World

on:
  workflow_dispatch:

jobs:
  hello-bash:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"

  hello-python:
    runs-on: ubuntu-latest
    steps:
      - run: print("Hello World!")

      
